### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by ThatOneCalculator** [cffnpwr/caffe-bruncher#1]
I'm planning on running this for prod, how do I configure it? (i.e. different port, etc)

**Comment by cffnpwr** [comment]
Added description of .env to README at 063ce36617b259a3cf7cdd70a5a083ee6ae9264f.

In case you are interested, here is a note on how to write .env in prod.

Create `.env.production` or `.env.production.local` and write the following

```
CK=[your consumer key for twitter API]
CS=[your consumer secret for twitter API]
TW_OAUTH_CALLBACK=[your server's URL]/twitter_callback # e.g. https://hogehoge.com/twitter_callback
MK_CALLBACK=[your server's URL]/misskey_callback # e.g. https://hogehoge.com/misskey_callback
```
