### ISSUE TITLE
macOSでコマンドキーで送信する

### ISSUE THREAD

**Issue by Hayao0819** [cffnpwr/caffe-bruncher#20]
MisskeyやTwitterと同じようにコマンドキーによる送信をサポートしてほしいです。

検証環境：M1 MacBook Pro 2020

**Comment by cffnpwr** [comment]
すえ(@souhait0614)がなんとかしてくれました
PR通したので数日中に動作確認して本番環境に反映されると思います

**Comment by Hayao0819** [comment]
ありがとうございます！！！
