### ISSUE TITLE
開発版の時はテーマや文章を変更する

### ISSUE THREAD

**Issue by L1n4r1A** [cffnpwr/caffe-bruncher#21]
正式版以外は文字列表示やカラー変更等で開発版である旨をわかりやすく表記できるように。
細かい仕様はしらないけど。

**Comment by cffnpwr** [comment]
ce7018779a96bbecde6996ff2e996b23d9a8a213 7bbbcf137862ee2d5b409f26e25f11252953ea98 で開発版では右上に開発版である旨を表示するようにしました

↓こんな感じになります
![image](https://user-images.githubusercontent.com/86540016/214600885-38e66ee9-a505-4194-9bbd-72da733cfcf2.png)
